use serde::Deserialize;
use std::path::PathBuf;

#[derive(Debug, Clone, Deserialize)]
pub struct AppConfig {
    /// URL du serveur Icon central
    pub server_url: String,

    /// Clé API machine (générée à l'enregistrement)
    pub api_key: Option<String>,

    /// Machine ID (attribué par le serveur)
    pub machine_id: Option<String>,

    /// Répertoire de stockage local
    pub data_dir: PathBuf,

    /// Clé de chiffrement de la BDD locale (SQLCipher)
    pub db_encryption_key: String,

    /// Port du proxy local
    pub proxy_port: u16,

    /// Intervalle heartbeat en secondes
    pub heartbeat_interval_secs: u64,

    /// Intervalle sync événements en secondes
    pub event_sync_interval_secs: u64,

    /// Taille max du batch d'événements
    pub event_batch_size: usize,

    /// Rétention locale max en jours
    pub local_retention_days: u32,

    /// Hash SHA-256 du certificat serveur (certificate pinning)
    pub server_cert_pin: Option<String>,

    /// Clé HMAC pour la signature des requêtes
    pub hmac_secret: Option<String>,

    /// URL WebSocket du serveur (base URL sans /app/{key})
    pub websocket_url: String,

    /// Clé applicative Reverb (Pusher protocol app key)
    pub reverb_app_key: Option<String>,

    /// Canal Reverb pour les mises à jour de règles
    pub reverb_channel: Option<String>,

    /// Enrollment key for initial registration (env ICON_ENROLLMENT_KEY or config file)
    pub enrollment_key: Option<String>,
}

impl AppConfig {
    /// Load configuration from the default config path, environment variables, and defaults.
    pub fn load() -> anyhow::Result<Self> {
        Self::load_from(None)
    }

    /// Load configuration from a specific config path (or the default if `None`).
    pub fn load_from(config_path_override: Option<&PathBuf>) -> anyhow::Result<Self> {
        let config_path = match config_path_override {
            Some(p) => p.clone(),
            None => Self::default_config_path(),
        };

        let settings = config::Config::builder()
            // Defaults
            .set_default("server_url", "https://icon.gs2e.ci")?
            .set_default("proxy_port", 8443_i64)?
            .set_default("heartbeat_interval_secs", 60_i64)?
            .set_default("event_sync_interval_secs", 30_i64)?
            .set_default("event_batch_size", 100_i64)?
            .set_default("local_retention_days", 7_i64)?
            .set_default("websocket_url", "wss://icon.gs2e.ci")?
            .set_default("reverb_app_key", "icon-local-key")?
            .set_default("reverb_channel", "icon.rules")?
            .set_default("data_dir", Self::default_data_dir().to_string_lossy().to_string())?
            .set_default("db_encryption_key", "CHANGE_ME_ON_INSTALL")?
            // Config file
            .add_source(config::File::from(config_path).required(false))
            // Environment variables (prefixed ICON_)
            .add_source(config::Environment::with_prefix("ICON"))
            .build()?;

        let config: AppConfig = settings.try_deserialize()?;
        Ok(config)
    }

    /// Return the platform-specific default config file path.
    pub fn default_config_path() -> PathBuf {
        if cfg!(target_os = "windows") {
            PathBuf::from(r"C:\ProgramData\Icon\config.toml")
        } else {
            PathBuf::from("/etc/icon/config.toml")
        }
    }

    fn default_data_dir() -> PathBuf {
        if cfg!(target_os = "windows") {
            PathBuf::from(r"C:\ProgramData\Icon\data")
        } else {
            PathBuf::from("/var/lib/icon")
        }
    }

    /// Generate a documented default config.toml file content with all fields and comments.
    pub fn generate_default_config_toml() -> String {
        let data_dir = Self::default_data_dir();

        format!(
r#"# =============================================================================
# Icon Agent Configuration
# =============================================================================
# This file is auto-generated by `icon-agent --generate-config`.
# All values shown are the defaults. Uncomment and modify as needed.
#
# Configuration can also be set via environment variables prefixed with ICON_.
# For example: ICON_SERVER_URL, ICON_PROXY_PORT, ICON_ENROLLMENT_KEY, etc.
# Environment variables take precedence over values in this file.
# =============================================================================

# URL of the central Icon server
server_url = "https://icon.gs2e.ci"

# Machine API key (assigned by the server during registration).
# Leave empty; this is auto-populated after registration.
# api_key = ""

# Machine ID (assigned by the server during registration).
# Leave empty; this is auto-populated after registration.
# machine_id = ""

# Local data storage directory (database, cache, etc.)
data_dir = "{data_dir}"

# Encryption key for the local SQLite database (SQLCipher).
# IMPORTANT: Change this to a strong random value on each installation.
db_encryption_key = "CHANGE_ME_ON_INSTALL"

# Port for the local HTTPS proxy interceptor
proxy_port = 8443

# Heartbeat interval in seconds (how often the agent pings the server)
heartbeat_interval_secs = 60

# Event synchronization interval in seconds
event_sync_interval_secs = 30

# Maximum number of events per sync batch
event_batch_size = 100

# Maximum local event retention in days
local_retention_days = 7

# SHA-256 hash of the server TLS certificate for certificate pinning.
# Leave commented out to use standard CA validation.
# server_cert_pin = "abcdef0123456789..."

# HMAC secret for request signing.
# Leave empty; this is auto-populated after registration.
# hmac_secret = ""

# WebSocket URL for real-time updates from the server
websocket_url = "wss://icon.gs2e.ci"

# Reverb (Pusher protocol) application key for WebSocket authentication
reverb_app_key = "icon-local-key"

# Reverb channel name for receiving rule update notifications
reverb_channel = "icon.rules"

# Enrollment key for initial agent registration.
# This key is validated by the server to authorize new agent registrations.
# Can also be set via the ICON_ENROLLMENT_KEY environment variable.
# enrollment_key = "your-enrollment-key-here"
"#,
            data_dir = data_dir.display(),
        )
    }
}
